import HeaderPage from "@/component/shared/header";
import "./globals.css";
import Footer from "@/component/shared/footer";
import Container from "@/component/UI/Container/Container";

export const metadata = {
  title: "MEDICARE",
  description: "Generated by MEDICARE app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <HeaderPage />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
