import HeaderPage from "@/component/shared/header";
import "./globals.css";
import Footer from "@/component/shared/footer";

export const metadata = {
  title: "MEDICARE",
  description: "Generated by MEDICARE app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderPage />
        {children}
        <Footer />
      </body>
    </html>
  );
}
